# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: xenial

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libssl-dev
      - libproj-dev
      - libgeos-dev
      - libhdf4-alt-dev
      - libhdf5-serial-dev
      - libgdal-dev
      - libnetcdf-dev

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - r-lib/pkgdown
  - ecmwf/caliver

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
