# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libhdf4-alt-dev
      - libhdf5-dev
      - libproj-dev
      - proj-bin
      - libgdal-dev
      - gdal-bin
      - libnetcdf-dev
      - netcdf-bin
      - libharfbuzz-dev
      - libfribidi-dev

r_packages:
  - lintr
  - covr
  - pkgdown

r_github_packages:
  - ecmwf/caliver

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
